export_languages:
  - ar
  - ca
  - da
  - es-ES
  - nl
  - fi
  - fr
  - de
  - he
  - it
  - nb
  - pl
  - ru
  - sv-SE
  - tr
  - uk
  - zh-CN
  - pt-PT
  - pt-BR
  - sk
files:
  - source: /FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
    translation: /FreeAPS/Sources/Localizations/Main/%osx_locale%.lproj/Localizable.strings
  - source: /Dependencies/rileylink_ios/RileyLinkKitUI/Base.lproj/Localizable.strings
    translation: /Dependencies/rileylink_ios/RileyLinkKitUI/%osx_locale%.lproj/Localizable.strings
  - source: /Dependencies/rileylink_ios/OmniKitUI/en.lproj/Localizable.strings
    translation: /Dependencies/rileylink_ios/OmniKitUI/%osx_locale%.lproj/Localizable.strings
  - source: /FreeAPS/Resources/Base.lproj/InfoPlist.strings
    translation: /FreeAPS/Resources/%osx_locale%.lproj/InfoPlist.strings
  - source: /Dependencies/LoopKit/LoopKit/Base.lproj/Localizable.strings
    translation: /Dependencies/LoopKit/LoopKit/%osx_locale%.lproj/Localizable.strings
  - source: /Dependencies/LoopKit/LoopKitUI/Base.lproj/Localizable.strings
    translation: /Dependencies/LoopKit/LoopKitUI/%osx_locale%.lproj/Localizable.strings
